spring:
  profiles:
    active:
    - dve
---
server:
  port: 8004
spring:
  application:
    name: USER-PROVIDER
  profiles: dve
---
server:
  port: 8001
spring:
  application:
    name: USER-PROVIDER
  profiles: test
