spring:
  profiles:
    active:
    - dve
---
server:
  port: 8001
spring:
  application:
    name: USER-PROVIDER
  profiles: dve
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8002
spring:
  application:
    name: USER-PROVIDER
  profiles: hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 9001
spring:
  profiles: ribbon
eureka:
  client:
   register-with-eureka: false #不注册到Eureka,不在注册中心显示
   service-url:
      defaultZone: http://localhost:7001/eureka
